spring:
  application:
    name: personal-assistant-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/personal_assistant
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080