import {
  HttpClient,
  HttpParams
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';


// ============================================================
// TASK TYPES
// ============================================================

export type TaskStatus =
  | 'TODO'
  | 'IN_PROGRESS'
  | 'COMPLETED'
  | 'CANCELLED';

export type TaskPriority =
  | 'LOW'
  | 'MEDIUM'
  | 'HIGH';


export interface TaskResponse {

  id: string;

  title: string;

  description: string | null;

  status: TaskStatus;

  priority: TaskPriority;

  dueDate: string | null;

  estimatedMinutes: number | null;

  aiGenerated: boolean;

  createdAt: string;

  updatedAt: string;

  captureId: string | null;

  goalId: string | null;
}


export interface CreateTaskRequest {

  title: string;

  description?: string;

  status?: TaskStatus;

  priority?: TaskPriority;

  dueDate?: string;

  estimatedMinutes?: number;

  captureId?: string;

  goalId?: string;
}


export interface UpdateTaskRequest {

  title?: string;

  description?: string;

  status?: TaskStatus;

  priority?: TaskPriority;

  dueDate?: string;

  estimatedMinutes?: number;

  goalId?: string | null;
}


// ============================================================
// TASK EXECUTION TYPES
// ============================================================

export type TaskExecutionStatus =
  | 'STARTED'
  | 'COMPLETED'
  | 'CANCELLED';


export interface CreateTaskExecutionRequest {

  feedback?: string;
}


export interface UpdateTaskExecutionRequest {

  status?: TaskExecutionStatus;

  feedback?: string;
}


export interface TaskExecutionResponse {

  id: string;

  taskId: string;

  startedAt: string;

  endedAt: string | null;

  status: TaskExecutionStatus;

  feedback: string | null;

  createdAt: string;
}


// ============================================================
// EXECUTION AI ANALYSIS
// ============================================================

export type ExecutionDifficulty =
  | 'EASY'
  | 'MEDIUM'
  | 'HARD';


export type ExecutionTimeAssessment =
  | 'UNDERESTIMATED'
  | 'ACCURATE'
  | 'OVERESTIMATED';


export type ExecutionBlocker =
  | 'NONE'
  | 'KNOWLEDGE_GAP'
  | 'TECHNICAL_ISSUE'
  | 'DISTRACTION'
  | 'UNCLEAR_REQUIREMENT'
  | 'EXTERNAL_DEPENDENCY'
  | 'OTHER';


export interface ExecutionAnalysisResponse {

  id: string;

  executionId: string;

  difficulty: ExecutionDifficulty;

  timeAssessment: ExecutionTimeAssessment;

  blocker: ExecutionBlocker;

  insight: string;

  suggestion: string;

  createdAt: string;
}


// ============================================================
// TASK PLANNING INTELLIGENCE
// ============================================================

export type PlanningConfidence =
  | 'NONE'
  | 'LOW'
  | 'MEDIUM'
  | 'HIGH';


export interface TaskPlanningInsightResponse {

  taskId: string;

  estimatedMinutes: number | null;

  averageActualMinutes: number | null;

  executionCount: number;

  planningExecutionCount: number;

  excludedExecutionCount: number;

  recommendedMinutes: number | null;

  confidence: PlanningConfidence;
}


// ============================================================
// AI DAILY PLANNER
// ============================================================

/**
 * One item generated by the AI planner.
 *
 * This matches the actual backend response:
 *
 * {
 *   "taskId": "...",
 *   "taskTitle": "...",
 *   "startAt": "...",
 *   "endAt": "...",
 *   "reason": "..."
 * }
 */
export interface AiPlanItem {

  taskId: string;

  taskTitle: string;

  startAt: string;

  endAt: string;

  reason: string;
}


/**
 * The actual AI-generated plan.
 *
 * Backend:
 *
 * "plan": {
 *   "planningDate": "2026-09-27",
 *   "items": [...]
 * }
 */
export interface AiPlanData {

  planningDate: string;

  items: AiPlanItem[];
}


/**
 * Persisted AI plan response.
 *
 * IMPORTANT:
 *
 * The backend returns:
 *
 * {
 *   "id": "...",
 *   "summary": "...",
 *   "plan": {
 *      "planningDate": "...",
 *      "items": [...]
 *   },
 *   "createdAt": "...",
 *   "updatedAt": "..."
 * }
 *
 * Therefore the property is `plan`,
 * NOT `planData`.
 */
export interface AiPlanResponse {

  id: string;

  summary: string;

  plan: AiPlanData;

  createdAt: string;

  updatedAt: string;
}


/**
 * Complete daily planner response.
 *
 * Backend:
 *
 * {
 *   "planningDate": "...",
 *   "availableFrom": "...",
 *   "availableUntil": "...",
 *   "plan": {
 *      ...
 *   }
 * }
 */
export interface DailyPlannerResponse {

  planningDate: string;

  availableFrom: string;

  availableUntil: string;

  plan: AiPlanResponse;
}


// ============================================================
// TASK SERVICE
// ============================================================

@Injectable({
  providedIn: 'root'
})
export class TaskService {

  private readonly baseUrl =
    'http://localhost:8080/api/tasks';

  private readonly dailyPlannerBaseUrl =
    'http://localhost:8080/api/daily-planner';


  constructor(
    private readonly http: HttpClient
  ) {}


  // ==========================================================
  // TASK CRUD
  // ==========================================================

  createTask(
    request: CreateTaskRequest
  ): Observable<TaskResponse> {

    return this.http.post<TaskResponse>(
      this.baseUrl,
      request
    );
  }


  getTasks(): Observable<TaskResponse[]> {

    return this.http.get<TaskResponse[]>(
      this.baseUrl
    );
  }


  getTask(
    taskId: string
  ): Observable<TaskResponse> {

    return this.http.get<TaskResponse>(
      `${this.baseUrl}/${taskId}`
    );
  }


  updateTask(
    taskId: string,
    request: UpdateTaskRequest
  ): Observable<TaskResponse> {

    return this.http.patch<TaskResponse>(
      `${this.baseUrl}/${taskId}`,
      request
    );
  }


  deleteTask(
    taskId: string
  ): Observable<void> {

    return this.http.delete<void>(
      `${this.baseUrl}/${taskId}`
    );
  }


  removeTaskFromGoal(
    taskId: string
  ): Observable<void> {

    return this.http.delete<void>(
      `${this.baseUrl}/${taskId}/goal`
    );
  }


  getTasksByCapture(
    captureId: string
  ): Observable<TaskResponse[]> {

    return this.http.get<TaskResponse[]>(
      `${this.baseUrl}/capture/${captureId}`
    );
  }


  // ==========================================================
  // TASK EXECUTIONS
  // ==========================================================

  getTaskExecutions(
    taskId: string
  ): Observable<TaskExecutionResponse[]> {

    return this.http.get<TaskExecutionResponse[]>(
      `${this.baseUrl}/${taskId}/executions`
    );
  }


  startTaskExecution(
    taskId: string,
    request: CreateTaskExecutionRequest = {}
  ): Observable<TaskExecutionResponse> {

    return this.http.post<TaskExecutionResponse>(
      `${this.baseUrl}/${taskId}/executions`,
      request
    );
  }


  updateTaskExecution(
    taskId: string,
    executionId: string,
    request: UpdateTaskExecutionRequest
  ): Observable<TaskExecutionResponse> {

    return this.http.patch<TaskExecutionResponse>(
      `${this.baseUrl}/${taskId}/executions/${executionId}`,
      request
    );
  }


  // ==========================================================
  // EXECUTION AI ANALYSIS
  // ==========================================================

  getExecutionAnalysis(
    taskId: string,
    executionId: string
  ): Observable<ExecutionAnalysisResponse> {

    return this.http.get<ExecutionAnalysisResponse>(
      `${this.baseUrl}/${taskId}/executions/${executionId}/analysis`
    );
  }


  analyzeExecution(
    taskId: string,
    executionId: string
  ): Observable<ExecutionAnalysisResponse> {

    return this.http.post<ExecutionAnalysisResponse>(
      `${this.baseUrl}/${taskId}/executions/${executionId}/analysis`,
      null
    );
  }


  // ==========================================================
  // ADAPTIVE PLANNING INTELLIGENCE
  // ==========================================================

  getPlanningInsight(
    taskId: string
  ): Observable<TaskPlanningInsightResponse> {

    return this.http.get<TaskPlanningInsightResponse>(
      `${this.baseUrl}/${taskId}/planning-insight`
    );
  }


  // ==========================================================
  // DAILY AI PLANNER
  // ==========================================================

  generateDailyPlan(
    planningDate: string,
    availableFrom: string,
    availableUntil: string
  ): Observable<DailyPlannerResponse> {

    let params = new HttpParams()
      .set(
        'planningDate',
        planningDate
      )
      .set(
        'availableFrom',
        availableFrom
      )
      .set(
        'availableUntil',
        availableUntil
      );

    return this.http.post<DailyPlannerResponse>(
      `${this.dailyPlannerBaseUrl}/generate`,
      null,
      {
        params
      }
    );
  }
}